config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users

  resources :documents, only: [:new, :create, :show] do
    resources :lines, only: [:show], param: "line_number"
  end

  root to: "documents#new"

  mount Sidekiq::Web => "/jobs"
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :lines

  validates_presence_of :name
end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :document

  validates_presence_of :document, :number
  validates_exclusion_of :content, in: [nil]
  validates_uniqueness_of :number, scope: :document
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def new
  end

  def create

    doc = Document.create!(
      name:        params[:document].original_filename,
      description: params[:description]
    )
    LineScanJob.perform_later doc, params[:document].path

    redirect_to doc
  end

  def show
    @document = Document.find params[:id]
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action { request.format = :json }

  def show
    @document = Document.find params[:document_id]
    @line     = @document.lines.find_by number: params[:line_number]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/documents/new.html.erb
<h1>Upload a document</h1>

<%= form_tag documents_path, multipart: true do %>
  <textarea name="description" placeholder="Add description" class="form-control"></textarea>
  <%= file_field_tag "document" %>
  <button class="btn btn-success">Upload</button>
<% end %>

app/views/documents/show.html.erb
<h1><%= @document.name %></h1>

<% if @document.completely_uploaded? %>
  <p>Uploaded <%= time_ago_in_words @document.created_at %> ago</p>
  <p><%= @document.line_count %> lines</p>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Line</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @document.lines.first(20).each do |l| %>
        <tr>
          <td><%= l.number %></td>
          <td><%= l.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
<% else %>
  <p>Waiting on upload to finish ... Refresh at will</p>
<% end %>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Lineserve"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Lineserve
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container
      .row
        = bootstrap_flash
        = yield